import { Dashboard } from "src/components/dashboard"
import Head from "next/head"
import type { NextPage } from "next"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <Dashboard />
    </>
  )
}

export default Home
